apiVersion: v1
kind: Service
metadata:
  name: mavenapp-service
  labels:
    app: mavenapp
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
    - name: http
      port: 80          # service port inside cluster
      targetPort: 8081  # container port
      nodePort: 30080   # port on your laptop (Docker Desktop node)
